name: Matrix Test Suite
on: 
  push:
    branches: ["main", "workflow"]
  pull_request:
    branches: ["main", "workflow"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Compile

        run: make all

      - name: Test

        run: make test